### ISSUE TITLE
Decide about "call" API

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-cpp#10]
Currently, a `session.call` will return a `boost::future` that resolves to `boost::any`.

We need to handle the cases where the RPC returns a `anyvec`, `anymap` or `anyvecmap`.

We might also need to handle how to return call result details ..

**Comment by davidchappelle** [comment]
This is no longer applicable. The call result details can just be returned through the wamp_call_result. I have added support for call options on my fork including progressive call results.
