### ISSUE TITLE
UDS should be excluded in Windows (CMake) if not compatible

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/autobahn-cpp#127]
Getting below build error on Windows MSVC 2015 for UDS project:
````
6>\workspace\autobahn-cpp\examples\uds.cpp(52): error C2039: 'wamp_uds_transport': is not a member of 'autobahn'

````

Looks like on Windows either `BOOST_ASIO_HAS_LOCAL_SOCKETS` should be set correctly, or the UDS example should be excluded from the list of projects in the CMake.

**Comment by oberstet** [comment]
Patches are welcome! I (and most devs here) don't have access to Windows / VS ..

Best would be to exclude the example for CMake and SConstruct. But only on Windows of course.

**Comment by KrishnaPG** [comment]
Would be happy to consider the patches - if I could get the project to build successfully first, that is. Been at it (on and off) for almost for a week+ (trying to resolve the openssl, msgpack, websocketpp what not).

The latest ones I am getting is:
````
6> LINK : fatal error LNK1104: cannot open file 'crypto.lib'
````
and only god knows where to get that `crypto.lib` from or where is it being used inside the code (yes - I pointed to openssl correcty in the cmake and, no - I could not see crypto.lib in the openssl folder files).

Looks like it is being used inside `wampcra` and `websocket_callee` projects. I have to look into it more deeply.

**Comment by KrishnaPG** [comment]
For those who are looking for help with OpenSSL with MSVC - here are the pre-built libraries that may help much: http://www.npcglib.org/~stathis/blog/precompiled-openssl/

**Comment by oberstet** [comment]
@KrishnaPG I am sorry to hear you are sinking so much time into this=(

Maybe @DZabavchik or @urbanpete has a hint. As mentioned, I don't use Windows anymore. I killed my last Windows box recently;)

Depending on your needs, you could also use our Docker images for AutobahnC++ (https://hub.docker.com/r/crossbario/) - Docker should run on Windows? If so, these images contain everything, and I do use these myself. `docker pull crossbario/autobahn-cpp` gets you started in no time.

You can also look at the Docker files creating these images, eg https://github.com/crossbario/crossbar-docker/blob/master/autobahn-cpp/Dockerfile.gcc - but I guess that won't be of much help on Windows.

**Comment by KrishnaPG** [comment]
Thank you @oberstet - Yes I pulled with docker and it is fine. But to understand the functionality better, I want to be able to debug the app (follow it step-by-step kind of) so that I can build apps around it.

I am thinking of either pulling a new docker image (that will have all dev environment setup where I can debug the code), or somehow make it work with Visual Studio, so that I can debug it.

No issues about investing the time into this @oberstet . There were times when I gave up completely and tried alternatives (such as bonefish etc..) - but they are having their own problems (incompatible messagepack versions so on...). 

Let me see where it goes. The fact I like about this (perhaps the reason I keep coming back to this) is: This is the only framework that is offering PubSub + RPC (and perhaps REST). Wish it was little bit easier on the windows side to setup. Or may be I just need to upgrade my dockers to include some cool dev environments (some UI based debuggers).

**Comment by DZabavchik** [comment]
@KrishnaPG, I have not checked VS projects for a few weeks.  It was building sample projects fine in VS2015.

**Comment by DZabavchik** [comment]
UDS project should not be built on Windows, as there are no UDS on that platform. Sample is inapplicable.

**Comment by oberstet** [comment]
@DZabavchik Thanks for watching this! Yeah, UDS should be excluded from both cmake and SConstruct. The other issue @KrishnaPG has with the Windows build in general - no clue. Whatever. Windows.

**Comment by KrishnaPG** [comment]
I am able to make the build get done successfully. Testing it. Will share the patch / fix etc. in some time.

**Comment by KrishnaPG** [comment]
Created pull request https://github.com/crossbario/autobahn-cpp/pull/128 with changes to CMake. Please feel free to extract the required portions as you see fit.
