### ISSUE TITLE
wamp_publish_options.* header is not installed

### ISSUE THREAD

**Issue by gajanak** [crossbario/autobahn-cpp#168]
wamp_publish_options.* introduced by commit 904b8c2100d537624287eac055457aa58fa3642d is not installed by make install.

Soory. My Fault.

Can someone please add
    ${CMAKE_CURRENT_SOURCE_DIR}/autobahn/wamp_publish_options.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/autobahn/wamp_publish_options.ipp
to CmakeList.txt  line 65.

Thanks.

**Comment by oberstet** [comment]
@gajanak np, thanks for contributing and for reporting this!

**Comment by raphaelpereira** [comment]
This seems closed
