### ISSUE TITLE
Waiting for future completion on unregister blocks indefinetly

### ISSUE THREAD

**Issue by mdegel** [crossbario/autobahn-cpp#175]
When calling unregister on a function you get a future, which I would expect to complete, when an unregister is received. However, attempting to wait for future completion blocks indefinetly.
The reason for this is the missing `process_unregistered(std::move(message));` in `wamp_session::on_message(wamp_message&& message)`, there is still a FIXME even though the method seems to have been implemented in Commit 4d4e74e5ff4e46c5da9fcab33d117f24a39a489b. 

Replacing FIXME with `process_unregistered(std::move(message));` made the future complete as expected.

So is there currently any reason for disabling process_unregister, or was this simply overlooked?

**Comment by oberstet** [comment]
yeah, this line https://github.com/crossbario/autobahn-cpp/blob/master/autobahn/wamp_session.ipp#L678 should actually call the (now implemented) `process_unregistered` function. so overlooked. a PR would be definitely welcome! =)

**Comment by mdegel** [comment]
PR is up. Wasnt sure about the FIXME reason, so i thought it would be a good thing to ask about it first ;)
