### ISSUE TITLE
build errors with msgpack 2.1.5

### ISSUE THREAD

**Issue by vitlav** [crossbario/autobahn-cpp#177]
autobahn/wamp_arguments.hpp:45:87: error: no matching function for call to 'msgpack::v2::object::object(std::array<msgpack::v2::object, 0ul>, std::nullptr_t)'
 static const msgpack::object EMPTY_ARGUMENTS(std::array<msgpack::object, 0>(), nullptr);

autobahn/wamp_arguments.hpp:46:77: error: no matching function for call to 'msgpack::v2::object::object(autobahn::wamp_kw_arguments, std::nullptr_t)'
 static const msgpack::object EMPTY_KW_ARGUMENTS(wamp_kw_arguments(), nullptr);

autobahn/wamp_rawsocket_transport.ipp:355:47: error: no matching function for call to 'msgpack::v2::unpacker::next(msgpack::v1::unpacked*)'
         while (m_message_unpacker.next(&result)) {

**Comment by mdegel** [comment]
Autobahn does not work with MsgPack >=2. You will need to use MsgPack 1.4.2 for now.

**Comment by oberstet** [comment]
dup of https://github.com/crossbario/autobahn-cpp/issues/95
