### ISSUE TITLE
Invocation results should be empty by default

### ISSUE THREAD

**Issue by mdegel** [crossbario/autobahn-cpp#178]
Currently when providing rpc functions, you are supposed to use `invocation->empty_result()` when the function does not return any result. This is somewhat an issue, since the wamp protocol expects a yield, which won't occur under these circumstances. Not providing any result in a rpc isn't that unusual though. Therefore I would consider it more suitable, to set invocation results to be empty by default.

@oberstet: Would anything speak against a change like this? If not I would create some PR for that.

**Comment by mdegel** [comment]
@oberstet: From my perspective it would be sufficient to add this:
```
// If still sendable, send default empty result
if(invocation->sendable()) {
    invocation->empty_result();
}
```
after this line:
https://github.com/crossbario/autobahn-cpp/blob/7cc5d37bb39bb1c682e1f6c020f62fefa75c0add/autobahn/wamp_session.ipp#L1077

**Comment by mdegel** [comment]
I initially expected a minor overhead for this behavior, since I thought, the empty result would always be called, as well as vanishing in the default send result (`send_result_fn()`). However the compiler (GCC 5.4) seems to differentiate between default functions and any user defined functions.

For reference this sample program:
```
#include <iostream>
#include <functional>

int main() {
    std::function<void()> f;
    std::cout << "f1 is " << static_cast<bool>(f) << std::endl;
    f = [](){};
    std::cout << "f2 is " << static_cast<bool>(f) << std::endl;
    f = std::function<void()>();
    std::cout << "f3 is " << static_cast<bool>(f) << std::endl;

    return 0;
}
```
will print:
```
f1 is 0
f2 is 1
f3 is 0
```
Therefore my solutions from before wouldn't even create any unnecessary overhead (except for the additional if).

**Comment by oberstet** [comment]
@mdegel I agree, actually, forgetting to call `invocation->empty_result()` can happen quite easily, and the issues resulting hard to debug. So adding a default behavior of sending an empty result seems to clearly improve developer experience. As far as I can see, the change you propose is also upwards compatible. So I'd be +1!

**Comment by mdegel** [comment]
@oberstet I have created a PR with the change.

**Comment by oberstet** [comment]
merged. thanks for contributing!
