### ISSUE TITLE
How should I handle a long-running RPC?

### ISSUE THREAD

**Issue by dvhwgumby** [crossbario/autobahn-cpp#182]
I have some functions that can take a long time to run -- potentially hours (basically you send some parameters and run a simulation).  While that is going on the system also wants to receive other RPCs that ask it for status of various things.

Given the ASIO threading model, how should I run this simulation?  My plan is to push a request on the program's main work queue with a future to supply the result, but I'm concerned about get() blocking the WAMP stack.  Should I simply start a lot of threads all running io_context::run()?  And if so, is it always safe for any thread to call autobahn::wamp_invocation::result()?

**Comment by oberstet** [comment]
No, you should (normally) not call `.get`, and there is also no need to use threads. This is async world .. checkout this https://github.com/crossbario/autobahn-cpp/blob/master/examples/callee_new.cpp
