### ISSUE TITLE
How to use same session for calling different remote procedure

### ISSUE THREAD

**Issue by anandacs005** [crossbario/autobahn-cpp#196]
Environment
Window 10
Crossbar io router

Problem Facing:

I want to maintain same session for calling different  remote procedure as per request.
Is there any sample available exampling how to maintain same session for multiple calls?

 Can anybody please help me out on this?

**Comment by oberstet** [comment]
Just add 2 calls in sequence:

```cpp
session->call("com.examples.calculator.add2", arguments, call_options).then(...);
session->call("com.examples.calculator.mul2", arguments, call_options).then(...);
```

https://github.com/crossbario/autobahn-cpp/blob/master/examples/caller.cpp#L104

when the 2nd call depends on the result from the 1st, the 2nd call needs to happen in the body of the 1st:

```cpp
session->call("com.examples.calculator.add2", arguments, call_options).then(
...
    session->call("com.examples.calculator.mul2", arguments, call_options).then(...);
...
);
```
