### ISSUE TITLE
CMake installation skips two files

### ISSUE THREAD

**Issue by dvhwgumby** [crossbario/autobahn-cpp#199]
The two files 
```
autobahn-cpp-18.4.1/autobahn/wamp_publish_options.hpp
autobahn-cpp-18.4.1/autobahn/wamp_publish_options.ipp
```
Are not copied into the target directory `include/autobahn` which means autobahn itself cannot compile.

**Comment by robinlinden** [comment]
It looks like this was resolved in d6659853e12c20931111eeb7e52a5cd125b87cb2? Is this just missing a new release?

**Comment by oberstet** [comment]
this is totally my fault, sorry - I missed this one https://github.com/crossbario/autobahn-cpp/issues/201. I am doing that now.

**Comment by oberstet** [comment]
but _this_ issue is definitely fixed via above commit, so I'm closing the issue
