### ISSUE TITLE
Rel 20.8.1

### ISSUE THREAD

**Issue by dvhwgumby** [crossbario/autobahn-cpp#201]
I would like to upgrade autobahn-cpp mainly so I can use a more modern msgpack-c, the installation bug, and, ideally, issue 198.  Any thoughts on this?

#198 makes installation and use easier, though is not crucial.

(The motivation is that we are trying to move to Conan if we can, and this way we could get the three packages together.  The standard Conan repo doesn't have an old copy of msgpack)

**Comment by oberstet** [comment]
absolutely! it's more than time for a fresh release ..

**Comment by oberstet** [comment]
alright, better late than never (sorry, missed this one ..):

* https://github.com/crossbario/autobahn-cpp/tree/v20.8.1
* https://hub.docker.com/r/crossbario/autobahn-cpp/tags?page=1&name=20.8.1
