### ISSUE TITLE
make methods on_ws_... protected on wamp_websocketpp_websocket_transport

### ISSUE THREAD

**Issue by pratman** [crossbario/autobahn-cpp#223]
To allow users to inherit from this class and:

- handle reconnection through on_ws_fail and on_ws_close
- catching the throw that happens on answering to goodbye message when process_goodbye does:
m_session_id = 0;
and calles send_message with default parameter session_established = true
and then send_message checks for:
if (session_established && !m_session_id) {
        throw no_session_error();
}

**Comment by pratman** [comment]
Should I split this issue?
As the throw is self-produced and seems to be a bug.
The request to make those methods protected instead of private is an enhancement to make the transport more versatile.

**Comment by oberstet** [comment]
the issue should describe the problem - not a proposed solution. and yes, if there are 2 problems, then there should be 2 issues. after that, we can discuss possible solutions. then we can select - if that involves changing public API, other users should have a change to state an opinion. then a PR is needed.

> rgd inheritance: unlikely we support that. implementation inheritance for users is wrong most of the time. but that doesn't matter: what is the problem in the first place? then we can discuss possible solutions.

**Comment by pratman** [comment]
Creating 2 issues for 2 different topics
