### ISSUE TITLE
Simple method invocation isn't working

### ISSUE THREAD

**Issue by davidchappelle** [crossbario/autobahn-cpp#39]
I wrote a simple client that provides a __boost::any add(anyvec, anymap)__ method. However, when I try to invoke that method as a wamp call the autobahn-cpp framework gives me the following error:

```
Could not process invocation - unimplemented endpoint type
NSt3__18functionIFN5boost3anyERKNS_6vectorIS2_NS_9allocatorIS2_EEEERKNS_3mapINS_12basic_stringIcNS_11char_traitsIcEENS4_IcEEEES2_NS_4lessISE_EENS4_INS_4pairIKSE_S2_EEEEEEEEE
PFN5boost3anyERKNSt3__16vectorIS0_NS1_9allocatorIS0_EEEERKNS1_3mapINS1_12basic_stringIcNS1_11char_traitsIcEENS3_IcEEEES0_NS1_4lessISD_EENS3_INS1_4pairIKSD_S0_EEEEEEE
```

Seems like this is more or less broken. Here is some simple example code showing how the typeid is not working as expected.

```
#include <functional>
#include <boost/any.hpp>
#define BOOST_THREAD_PROVIDES_FUTURE
#define BOOST_THREAD_PROVIDES_FUTURE_CONTINUATION
#define BOOST_THREAD_PROVIDES_FUTURE_WHEN_ALL_WHEN_ANY
#include <boost/thread/future.hpp>
#include <iostream>
#include <vector>

typedef std::map<std::string, boost::any> anymap;
typedef std::vector<boost::any> anyvec;
typedef std::pair<anyvec, anymap> anyvecmap;

typedef std::function<boost::any(const anyvec&, const anymap&)> endpoint_t;
typedef std::function<anyvec(const anyvec&, const anymap&)> endpoint_v_t;
typedef std::function<anymap(const anyvec&, const anymap&)> endpoint_m_t;
typedef std::function<anyvecmap(const anyvec&, const anymap&)> endpoint_vm_t;

typedef std::map<uint64_t, boost::any> endpoints_t;

boost::any add2(const anyvec& args, const anymap& kwargs)
{
    return 1 + 1;
}

int main(int argc, char** argv)
{
    endpoints_t endpoints;
    endpoints[0] = &add2;

    boost::any func = &add2;

    std::cerr << "typeid for raw function: " << typeid(add2).name() << std::endl;
    std::cerr << "typeid for variant function: " << func.type().name() << std::endl;
    std::cerr << "typeid for endpoint_t function: " << typeid(endpoint_t).name() << std::endl;

    return 0;
}
```

**Comment by davidchappelle** [comment]
I think I see what the problem is. We used to have a concrete __session::provide(...)__ method for each of the endpoint types. However, a recent change introduced a templated method to reduce this to a single __session::provide(...)__ method. In doing so, we are not actually getting types of **endpoint_** being stored. Compatible function pointers/signatures yes but distinctly different objects.

**Comment by stopthatcow** [comment]
I am seeing this behavior as well. Are there any regression tests that could be run to check for this sort of thing prior to merging to master?

**Comment by davidchappelle** [comment]
This is fixed in my fork: Implemented in my fork: https://github.com/davidchappelle/AutobahnCpp

**Comment by stopthatcow** [comment]
Thank, your fork looks quite promising! I love the handler/invocation change that allows forwarding of the call to an async handler. It looks like the future handling is a bit broken in the base version as the returned future is immediately waited on in the process_invocation handler.

**Comment by davidchappelle** [comment]
This issue is no longer relevant.
