### ISSUE TITLE
crossbar-autobahncpp metaevents

### ISSUE THREAD

**Issue by funnydoggie** [crossbario/autobahn-cpp#47]
How to get router metaevents of session list and which sessionid calling an RPC in cpp?
I tried to find an equivalent cpp function to the JS session.call("wamp.registration.list").then(session.log, session.log).
In JS router, "disclose_me" can be set in 3rd options arg of session.register(procedure, endpoint, options). But in cpp, the equivalent method to "register" is "provide", i.e. auto r1 = session.provide("com.example.add2", &add2), and has only two options.

Also tried looking through the hpp files, and the online docs (javascript metaevents), and also read this https://github.com/tavendo/WAMP/issues/157

**Comment by oberstet** [comment]
There is nothing special with the WAMP meta API: simply issue a call to `wamp.whatever`
