### ISSUE TITLE
subscriber.cpp produce Warning: event handler threw exception

### ISSUE THREAD

**Issue by alt1972** [crossbario/autobahn-cpp#60]
It is produced by:  std::cerr << "received event: " << event.argument<uint64_t>(0) << std::endl;

To fixt it change uint64_t => std::string  like this: event.argument<std::string>(0)

Regards,

**Comment by alt1972** [comment]
It is produced by:   std::cerr << "received event: " << event.argument<uint64_t>(0) << std::endl;

To fixt it change uint64_t => std::string like this: event.argument<std::string>(0)

now it's ok! ;-)


Regards,

**Comment by oberstet** [comment]
clang does not produce any warning during building: https://github.com/crossbario/autobahn-cpp/tree/master/examples#build
