### ISSUE TITLE
wampcra / ticket authentication 

### ISSUE THREAD

**Issue by brianbirke** [crossbario/autobahn-cpp#61]
Hello, 

I have tried ( have done, but prefer to call it at try :-) ) to implement the missing bits for a wampcra and ticket authentication. 

I am a little cold with c++ ( not really used it for 7 years ), and newer touched C++11. So the implementation is merely a copy-paste from other code sections - which should prove its quality :-) - but anyway if some proper one could take a fast look. 

My mission is to put it in such a condition, it can be merged back into this repositary. 

The code is located :
repositary: https://github.com/brianbirke/AutobahnCpp.git
branch : auth

Remarks about the code: 
- I added a simple interface on the session - just to make it more obvious of how to use authentication. This might or might not be a good idea. 
- I am using some openssl crypto-functions - making dependencies even if authentication is not used. It is not really fair, is it?? :-). Please comment on how to avoid this??
- else, it is coded with crossbar as the reference - and it works with that. 

Best Regards
Brian Birke.

**Comment by oberstet** [comment]
I've skimmed over .. nice, nice! I would like to merge this in general.

My two itches:

* need to decide upon OpenSSL dependency (if so, making it optional is another thing)
* need to review / hash out the new public API added

Ok. OpenSSL. We need SSL/TLS encryption anyway.  Boost/ASIO, which AutobahnCpp is based on provides [this](http://www.boost.org/doc/libs/1_59_0/doc/html/boost_asio/reference/ssl__stream.html), and that works via OpenSSL. So doing additional things (like the WAMP-CRA crypto stuff) with OpenSSL does not introduce an additional wheel. Which is good.

On the negative side, OpenSSL sucks a little .. in particular when used from C++. In the past, I have used [Botan](http://botan.randombit.net/) with great success and pleasure. It's _native_ C++ throughout. But it would induce more work to make it fly on top of ASIO.

Let's discuss this point first, and the go on, sounds good?

**Comment by brianbirke** [comment]
The 3 functions I added to the session, I think is a spin off, of how I use the sessions. Because I was implementing a two-factor authentication, I had to use 2 sessions - one wampcra and one ticket authentication. So it was for my convenience - to avoid create 2 new session classes, and overwrite the "join" and "challenge" functions... I am really not insisting on them. For consistency it better to be closer to autobahnPython, maybe not for convenience :-)...
Maybe the process_challenge should call a onChallenge function ( to be overwritten ) with a more convenient input arguments.... 

About the crypto functions, I agree with you, it was not very funny to implement the 2 functions needed using openssl crypto.
I added an implementation of the functions using the Botan lib. Much better! Unfortunately the version installed on my computer was 1.10 - the old release branch.  If decided using Botan - I will lift the implementation using 1.11. 

So, I think you should decide if you want the 3 functions on the session. Convenience vs. Consistency.... 
I am positive on using Botan, it seems it can be compiled almost all platforms too.

**Comment by jpetso** [comment]
Botan seems nice in general but in many cases it will add yet another dependency to applications, when OpenSSL is already required by other dependencies.

Would it be possible to make CRA an optional feature and provide the implementation by an interface provided to the session? Then we could have OpenSSL versions, Botan versions or whatever other crypto libraries are out there, and for people who don't use CRA no new dependency needs to be pulled in.

**Comment by brianbirke** [comment]
Disclamer: I am close to ice cold developing c++, not used it for years..So take this elaborating with both salt and pebber.....

Seperate the authentication method:

There are only 3 places where the authentication touched the code:
- in the join method
- in the message dispatcher function "got_message", that just call a process_challenge function
- a process_challenge function. 

The join method needs to pack information about the auth-method and principal. 
For maintain purposes, I think the "join" function should just be added the 2 arguments
( As I see the MsgPack, it is difficult to mix partial implementations (?) ). 

The "got_message" function needs one line change. Again for the purpose of maintainment, let the got_message function call a default implemented process_challenge, that needs no crypto.

- a default process_challenge version could just raise an protocol error. 
- or better, it could do like the python version, call an "onChallenge" with the message, 
  the onChallange version is then supposed to return a signature. The the process_challenge function then send the signature in an Authentication message. ( a default onChallenge raises an protocol error )

The missing bits is then a process_challenge ( or onChallenge ) function. 
This a developer can add by inherence (maybe mixin) using the utility functions in "wamp_auth_utils_botan.hpp" or "wamp_auth_utils_openssl.hpp". 
How to fetch the "secret" is up to the developer...no extra interface for that....
Quite simelar to the python version....

**Comment by oberstet** [comment]
I've looked over your Botan implementation .. looks nicer, yes. Nevertheless, I'd go with your OpenSSL implementation for now, since it doesn't add another dependency above what's needed for TLS anyway.

Regarding API, this is what I think would work and fit into the current state of the code:

1. The `wamp_session.join` method should take additional, optional parameters: `join(const std::string& realm, const std::vector<std::string>& authmethods, const std::string& authid)`
2. There should be a private method `wamp_session.process_challenge` to handle incoming `CHALLENGE` messages.
3. There should be a user callback `boost::future<wamp_authenticate> wamp_session.on_challenge(const wamp_challenge& challenge)`
4. There should be a utility functions `compute_wcs`, `generate_wcs`, `derive_key` and `pbkdf2` roughly modeled after https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/auth.py

**Comment by brianbirke** [comment]
I can try to implement this - within the next few days... little busy...If I understand the solution right, 
I agree this a very good solution.
 
Just for me to not waste my time - I prefer to waste yours :-) - just a recap.

The flow during this authentication scheme will be: 
1) join sent a vector of authmethods and a principal to crossbar/router.
2) the crossbar/router respons with a challenge message.
3) this message is parsed in a "process_challenge" on the session. 
4) an object wamp_challenge ( to be defined ) - is created in the process_challenge function
5) a function on_challenge is called with the wamp_challenge object, and a future is returned. 
( the developer implementing the on_challange to fit his context, must ensure lifetime etc for the future )
6) when future "fires" in the "process_challenge" function, it reveals an wamp_authenticate object ( to be defined )
7) The process_challenge reads the information from the wamp_authenticate object, and send an AUTHENTICATE message back to the router...

understood right??

**Comment by brianbirke** [comment]
I succeded to find some time to implement a solution as described above. 

It is located in 
branch : auth2
repos : https://github.com/brianbirke/AutobahnCpp.git

Feel free to comment, so I can improve it....

**Comment by jpetso** [comment]
Do you want to open a pull request for that branch? GitHub makes it easier to review and comment on the changes that way, especially when your changes consist of several commits.

**Comment by brianbirke** [comment]
I will "flex" this code on a windows platform next week. As soon I have confirmed it works, or it fixed why it does not - I will make a pull request! no problem!

**Comment by oberstet** [comment]
has been merged
