### ISSUE TITLE
Relicense to Boost

### ISSUE THREAD

**Issue by jpetso** [crossbario/autobahn-cpp#62]
msgpack-c has been relicensed to the Boost license as per https://github.com/msgpack/msgpack-c/issues/366 and @oberstet has previously indicated that he'd like to change the license of autobahn-cpp from Apache to a more liberal one in order to allow use with GPL-licensed software (see msgpack-c issue for a chart).

Now that msgpack-c is Boost licensed and its 1.3.0 version has been released with the new license, this change could now happen in autobahn-cpp as well.

**Comment by oberstet** [comment]
@jpetso I agree (already did, but just to make it clear). Lets change to Boost license as msgpack-c did. Users then will only have to deal with one license ..

**Comment by oberstet** [comment]
As you @jpetso agree, me and @goeddea will also without doubt, I think Dave @davidchappelle also agreed already? Not sure though ..

**Comment by jpetso** [comment]
Dave's code (as well as mine) has Topology copyright. Topology LP agrees to have all of its code in autobahn-cpp to date relicensed to Boost.

**Comment by goeddea** [comment]
I agree to relicense whatever contributions I've made to the Boost license.

**Comment by goeddea** [comment]
@jrogers @taion @IvaKom @bb4242 @anton-matosov - Are you also OK with the relicensing? Please leave a short comment indicating your agreement.

**Comment by jrogers** [comment]
Yes I'm fine with it

**Comment by taion** [comment]
I agree.

**Comment by davidchappelle** [comment]
I am in agreement.

**Comment by anton-matosov** [comment]
I agree

**Comment by bb4242** [comment]
I agree.

**Comment by brianbirke** [comment]
I agree.

**Comment by oberstet** [comment]
For the record: all contributors but @IvaKom responded and agreed. The 2 commits done by @IvaKom (https://github.com/crossbario/autobahn-cpp/commits?author=IvaKom) are only few lines, and strictly bug fixing. This isn't a substantial, creative contribution in terms of the law, so I think we are safe.
