### ISSUE TITLE
Example Publisher fails with bonefish 

### ISSUE THREAD

**Issue by Afra-Felix** [crossbario/autobahn-cpp#64]
When trying example from master/examples with bonefish router. 
./bonefish -w 8080 -t 8000 -r default -d
Publisher example does not work as expected.

1. Bonefish and Python Publisher works - 

[rawsocket_transport.cpp:39][send_message] sending message: event
[wamp_message_processor.cpp:46][process_message] processing message: publish
[wamp_broker.cpp:108][process_publish_message] session [3648815945442074,default,open], publish [12, {}, com.examples.subscriptions.topic1, [12], nil]
[wamp_broker.cpp:141][process_publish_message] session [7090515283965860,default,open], event [1, 2156265064422709, {}, [12], nil]
[rawsocket_transport.cpp:39][send_message] sending message: event
[wamp_message_processor.cpp:46][process_message] processing message: goodbye
[wamp_router_impl.cpp:211][process_goodbye_message] session [3648815945442074,default,closed], goodbye [{}, wamp.close.normal]
[websocket_transport.cpp:39][send_message] sending message: goodbye
[wamp_dealer.cpp:79][detach_session] detach session: session [3648815945442074,default,closed]
[wamp_dealer.cpp:84][detach_session] cleaning up session registrations
[wamp_dealer.cpp:113][detach_session] cleaning up pending caller invocations
[wamp_dealer.cpp:133][detach_session] cleaning up pending callee invocations

2. Bonefish and Cpp Publisher fails - 

[rawsocket_transport.cpp:39][send_message] sending message: event
[wamp_message_processor.cpp:46][process_message] processing message: publish
[wamp_broker.cpp:108][process_publish_message] session [3648815945442074,default,open], publish [12, {}, com.examples.subscriptions.topic1, [12], nil]
[wamp_broker.cpp:141][process_publish_message] session [7090515283965860,default,open], event [1, 2156265064422709, {}, [12], nil]
[rawsocket_transport.cpp:39][send_message] sending message: event
[wamp_message_processor.cpp:46][process_message] processing message: goodbye
[wamp_router_impl.cpp:211][process_goodbye_message] session [3648815945442074,default,closed], goodbye [{}, wamp.close.normal]
[websocket_transport.cpp:39][send_message] sending message: goodbye
[wamp_dealer.cpp:79][detach_session] detach session: session [3648815945442074,default,closed]
[wamp_dealer.cpp:84][detach_session] cleaning up session registrations
[wamp_dealer.cpp:113][detach_session] cleaning up pending caller invocations
[wamp_dealer.cpp:133][detach_session] cleaning up pending callee invocations

Not sure if this is a autobahn-cpp issue or a bonefish one. since @davidchappelle  is also a contributor here, Im submitting it here.

**Comment by davidchappelle** [comment]
I'll take a look later this evening.

**Comment by meejah** [comment]
Without digging at all: is it just where the message-numbers start? Bonefish rejects 0 so the numbers must start at 1 (AutobahnPython was starting at 0, which meant "nothing" worked w/ bonefish).

**Comment by Afra-Felix** [comment]
I ran the example code without modification and it publish only once.

**Comment by davidchappelle** [comment]
If you look at the publisher code it only publishes once and then returns from main so that is expected behaviour. I am not seeing any issues here. I am testing against latest `bonefish` and `AutobahnCpp`.

Bonefish Output
```
dchappelle@orion:build$ ./daemon/bonefish -r default -t 9000 -d
[rawsocket_server_impl.cpp:94][start] starting rawsocket server
[wamp_message_processor.cpp:46][process_message] processing message: hello
[wamp_router_impl.cpp:107][attach_session] attaching session: session [7090515283965860,default,none]
[wamp_dealer.cpp:62][attach_session] attach session: session [7090515283965860,default,none]
[wamp_broker.cpp:51][attach_session] attach session: session [7090515283965860,default,none]
[wamp_router_impl.cpp:163][process_hello_message] session [7090515283965860,default,none], hello [default, {"roles":{"caller":{"features":{"call_timeout":true}}, "callee":{"features":{"call_timeout":true}}, "publisher":{}, "subscriber":{}}}]
[wamp_router_impl.cpp:191][process_hello_message] session [7090515283965860,default,open], welcome [7090515283965860, {"roles":{"dealer":{"features":{"call_timeout":true}}, "broker":{}}}]
[rawsocket_transport.cpp:39][send_message] sending message: welcome
[wamp_message_processor.cpp:46][process_message] processing message: subscribe
[wamp_broker.cpp:163][process_subscribe_message] session [7090515283965860,default,open], subscribe [1, {}, com.examples.subscriptions.topic1]
[wamp_broker.cpp:196][process_subscribe_message] session [7090515283965860,default,open], subscribed [1, 1]
[rawsocket_transport.cpp:39][send_message] sending message: subscribed
[wamp_message_processor.cpp:46][process_message] processing message: hello
[wamp_router_impl.cpp:107][attach_session] attaching session: session [2257228500326156,default,none]
[wamp_dealer.cpp:62][attach_session] attach session: session [2257228500326156,default,none]
[wamp_broker.cpp:51][attach_session] attach session: session [2257228500326156,default,none]
[wamp_router_impl.cpp:163][process_hello_message] session [2257228500326156,default,none], hello [default, {"roles":{"caller":{"features":{"call_timeout":true}}, "callee":{"features":{"call_timeout":true}}, "publisher":{}, "subscriber":{}}}]
[wamp_router_impl.cpp:191][process_hello_message] session [2257228500326156,default,open], welcome [2257228500326156, {"roles":{"dealer":{"features":{"call_timeout":true}}, "broker":{}}}]
[rawsocket_transport.cpp:39][send_message] sending message: welcome
[wamp_message_processor.cpp:46][process_message] processing message: publish
[wamp_broker.cpp:108][process_publish_message] session [2257228500326156,default,open], publish [1, {}, com.examples.subscriptions.topic1, ["hello"], nil]
[wamp_broker.cpp:141][process_publish_message] session [7090515283965860,default,open], event [1, 7090515283965860, {}, ["hello"], nil]
[rawsocket_transport.cpp:39][send_message] sending message: event
[wamp_message_processor.cpp:46][process_message] processing message: goodbye
[wamp_router_impl.cpp:211][process_goodbye_message] session [2257228500326156,default,closed], goodbye [{}, wamp.error.close_realm]
[rawsocket_transport.cpp:39][send_message] sending message: goodbye
[wamp_dealer.cpp:79][detach_session] detach session: session [2257228500326156,default,closed]
[wamp_dealer.cpp:84][detach_session] cleaning up session registrations
[wamp_dealer.cpp:113][detach_session] cleaning up pending caller invocations
[wamp_dealer.cpp:133][detach_session] cleaning up pending callee invocations
[wamp_broker.cpp:66][detach_session] detach session: 0x1ec5800
[rawsocket_connection.hpp:302][handle_system_error] connection closed: asio.misc:2
```

AutobahnCpp Subscriber Output
```
dchappelle@orion:build$ ./examples/subscriber -d -p 9000
realm: default
starting io service
connected to server
RawSocket handshake reply received
rawsocket handshake: using msgpack serializer
rawsocket handshake: start wamp async
RX preparing to receive message ..
session started
TX message (105 octets) ...
TX message sent (109 / 109 octets)
RX message (59 octets) ...
RX message received.
RX WAMP message: [2, 7090515283965860, {"roles"=>{"dealer"=>{"features"=>{"call_timeout"=>true}}, "broker"=>{}}}]
RX preparing to receive message ..
joined realm: 7090515283965860
TX message (39 octets) ...
TX message sent (43 / 43 octets)
RX message (4 octets) ...
RX message received.
RX WAMP message: [33, 1, 1]
RX preparing to receive message ..
RX message (20 octets) ...
RX message received.
RX WAMP message: [36, 1, 7090515283965860, {}, ["hello"]]
Warning: event handler threw exception
RX preparing to receive message ..
```

AutobahnCpp Publisher Output
```
dchappelle@orion:build$ ./examples/publisher -d -p 9000
starting io service
connected to server
RawSocket handshake reply received
rawsocket handshake: using msgpack serializer
rawsocket handshake: start wamp async
RX preparing to receive message ..
session started
TX message (105 octets) ...
TX message sent (109 / 109 octets)
RX message (59 octets) ...
RX message received.
RX WAMP message: [2, 2257228500326156, {"roles"=>{"dealer"=>{"features"=>{"call_timeout"=>true}}, "broker"=>{}}}]
RX preparing to receive message ..
joined realm: 2257228500326156
event published
TX message (46 octets) ...
TX message sent (50 / 50 octets)
TX message (26 octets) ...
TX message sent (30 / 30 octets)
RX message (30 octets) ...
RX message received.
RX WAMP message: [6, {}, "wamp.error.goodbye_and_out"]
RX preparing to receive message ..
left session (wamp.error.goodbye_and_out)
stopped io service
stopped session
```


FWIW the caller and callee examples are also working for me as expected.

**Comment by Afra-Felix** [comment]
Oh I  just missed -d options thats made it look like theres no output at all. Thanks

**Comment by Afra-Felix** [comment]
Im reopening again since I see still there is something not working. If you see the subsriber example code. 
```
void topic1(const autobahn::wamp_event& event) {
    std::cerr << "received event: " << event.argument<uint64_t>(0) << std::endl;
}
```
you never see this calback topic being called when using publisher example but it works perfectly when using a python publisher. 

You also get exception in AutobahnCpp Subscriber 
```
Warning: event handler threw exception 
```
For Python Publisher I get this
```
received event  1
```
