### ISSUE TITLE
websocket over HTTP via JSON

### ISSUE THREAD

**Issue by CepGamer** [crossbario/autobahn-cpp#68]
I ran into an issue that library cant work via default websocket protocol on a mixed http/wamp server that doesn't support msgpack.

To solve such issue I have created my own fork (https://github.com/CepGamer/autobahn-cpp, not finished yet) that creates websocket connection over http (using http upgrade request) and communicates using this socket. Also I had to translate JSON messages to and from msgpack by creating a wrap (changed get_message_body() function to produce msgpack object from json string and send() function to do the opposite).

It's messed up and not yet ready (lots of copy/paste and hardcode), but I'm planning to finish it. I wanted to know, whether such additions is needed or maybe I am doing it wrong (maybe there is a better way :) ) or I just haven't found it in the lib.

Regards,
Sergei Bolotov

**Comment by jpetso** [comment]
As a suggestion, you might want to do rebases instead of merges if the intention is to get your branch merged back into upstream autobahn-cpp.

We've also recently split out https://github.com/tplgy/json-msgpack from bonefish which handles JSON/msgpack conversions with a minimal amount of extra copies, we should probably also move the WAMP-specific binary handling into that project and see if it can be switched to the Boost license as well.

**Comment by CepGamer** [comment]
May I ask you a couple of questions?

What would you recommend on how to implement switch between websocket frames and raw byte exchange via TCP?
Also, I'm using websocketpp to construct frames which introduces new dependency, maybe I should use some other library?

**Comment by oberstet** [comment]
@CepGamer from the spec (on rawsocket handshake):

   The _first octet_ is a magic octet with value "0x7F".  This value is
   chosen to avoid any possible collision with the first octet of a
   valid HTTP request (see here [6] and here [7]).  No valid HTTP
   request can have "0x7F" as its first octet.

      By using a magic first octet that cannot appear in a regular HTTP
      request, WAMP-over-RawSocket can be run e.g. on the same TCP
      listening port as WAMP-over-WebSocket or WAMP-over-LongPoll.

rgd websocket: websocketpp is just fine. I would not use a different lib nor reinvent the wheel.

**Comment by Bobface** [comment]
So you can not connect to servers with http/wamp mixed protocols? I think in AutobahnJS it works, doesn't it?

**Comment by CepGamer** [comment]
@Bobface Yes, it works in JS and Python (the ones I checked), but, unfortunately, I may only use C++ in my code.

**Comment by oberstet** [comment]
As mention, RawSocket has facilities to support running besides WebSocket on one TCP port.

This is not using HTTP upgrade mechanism, and is a router-side feature - there is nothing to implement in WAMP clients.
