### ISSUE TITLE
Merge outstanding pull requests

### ISSUE THREAD

**Issue by davidchappelle** [crossbario/autobahn-cpp#81]
@oberstet  Numerous pull requests now queued up. Can you take a look next change you get. All fairly trivial build issues and a few memory leak fixes.

**Comment by oberstet** [comment]
Sorry, I won't find time soon.

**Comment by davidchappelle** [comment]
I have all of these patches all split out onto separate branches as
requested previously. Until they are merged upstream I can't incorporate
them into my downstream branch otherwise I will likely get merge conflicts
later. Probably only 2-3 minutes worth or merging to be done here.

**Comment by oberstet** [comment]
@davidchappelle ok, all (but one tiny one) merged. Sorry, I didn't look closely .. thanks for splitting up everything - I appreciate! Much easier to process.

**Comment by davidchappelle** [comment]
Thanks Tobias. I really appreciate it. I fixed the merge conflict on that
last one.
The rest of the commits for the transport abstraction work will start
sometime
next week. I'll split them up as small as I can into a logical sequence.

**Comment by oberstet** [comment]
@davidchappelle awesome, thanks!
