### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by Sync-my-L2P** [crossbario/autobahn-cpp#83]
1. The notes about in the examples in the Readme are not up-to-date. The referenced files dont exist.
2. Many Functions, which are called from index.html, are not existing.
3. Example code is not able to start a session on a current crossbar.io router (nothing happens, no error)

**Comment by Sync-my-L2P** [comment]
"If you find that something is broken, then please file an issue (or fix it and send us a pull request)."

You forgot to add "If you are lucky, we won't close your issue without any comment"

**Comment by ecorm** [comment]
@Sync-my-L2P , I do understand that from your point-of-view, this might appear to be rather rude behavior.

@oberstet has had problems before closing issues by accident. Let's hope this is what happened here.

**Comment by oberstet** [comment]
We've recently merged a lot of code from contributors - and I probably haven't looked closely enough. Seems to have broken some things (eg examples). Well.

Rgd the README: I've removed the links to the examples. Rgd the default CB C++ hello template: yep. please see https://github.com/crossbario/crossbar/issues/374

Other than that: bug reports .. without knowing what exactly was tried (exact versions, what examples, ...) and showing logs, it's difficult in general. "Something does not work" isn't helpful - how would I reproduce the issue? Hence I just close. I agree that this not nice and there should be a better, but also quick way. Unfortunately, GitHub does not allow this: have a small hint as a note to an issue submitter:

"Please only file bugs and enhancements, not questions. If you file a bug, include at least X, Y, Z info. If you file an enhancement, please describe your use case - not an implementation."

**Comment by ecorm** [comment]
@oberstet , I can understand how the lack of fields for version number, component, etc (like Bugzilla) would be frustrating for you. I was curious to know if there's a way to add such fields to GH issues and stumbled upon this: https://github.com/kentcdodds/issue-template

**Comment by oberstet** [comment]
FWIW, all examples work for me with Crossbar.io trunk at least: https://github.com/crossbario/autobahn-cpp/tree/master/examples

**Comment by oberstet** [comment]
@ecorm nice, but it requires read+**write** access to all repos. no way.

The Crossbar.io `hello:cpp` template is ported to the current AutobahnCpp code now. Works for me. Anyway .. back to Python;) This C++ line-noise is killing me ..
